"""x handle column added

Revision ID: 052a229ff5b4
Revises: d43af77927c3
Create Date: 2025-06-18 17:14:21.745346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '052a229ff5b4'
down_revision: Union[str, Sequence[str], None] = 'd43af77927c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timemarket', sa.Column('x', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timemarket', 'x')
    # ### end Alembic commands ###
